### ISSUE TITLE
Master broken NERDtree <C-n> map

### ISSUE THREAD

**Issue by brunoadacosta** [terryma/vim-multiple-cursors#138]
My .vimrc

```
set nocompatible              " be iMproved, required
filetype off " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'

" Bundles
Plugin 'tpope/vim-surround'
Plugin 'ervandew/supertab'
Plugin 'Lokaltog/vim-powerline'
"Plugin 'bling/vim-airline'
Plugin 'vim-ruby/vim-ruby'
Plugin 'tpope/vim-rails'
Plugin 'Keithbsmiley/rspec.vim'
Plugin 'tpope/vim-endwise'
Plugin 'edsono/vim-matchit'
Plugin 'kien/ctrlp.vim'
Plugin 'Raimondi/delimitMate'
Plugin 'tpope/vim-commentary'
Plugin 'mattn/webapi-vim'
Plugin 'mattn/gist-vim'
Plugin 'danro/rename.vim'
Plugin 'thoughtbot/vim-rspec'
Plugin 'aaronj1335/underscore-templates.vim'
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'bridgeutopia/snipmate-snippets'
Plugin 'garbas/vim-snipmate'
Plugin 'vim-scripts/bufkill.vim'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'scrooloose/nerdtree'
Plugin 'pangloss/vim-javascript'
Plugin 'jeyb/vim-jst'
Plugin 'terryma/vim-multiple-cursors' 
"Plugin 'scrooloose/syntastic'
Plugin 'gorkunov/smartpairs.vim'
Plugin 'pbrisbin/vim-mkdir'
Plugin 'fatih/vim-go'
Plugin 'elixir-lang/vim-elixir'
Plugin 'carlosgaldino/elixir-snippets'
Plugin 'rking/ag.vim'

call vundle#end()  

filetype plugin indent on
syntax on

set history=100
set nobackup
set noswapfile
set pastetoggle=<F6>
set mouse=a
set encoding=utf-8

set title
set titleold=
set ruler
set number

set backspace=2        " indent,eol,start
set whichwrap+=<,>,h,l
set shortmess=aTsI     " see :help shortmess
set noerrorbells
set visualbell
set scrolloff=3
set sidescroll=3

set autoread
set splitright
set splitbelow
set hidden
set clipboard=unnamed

set timeoutlen=500
set showmatch
set matchtime=1
set hlsearch
set incsearch
set ignorecase
" set list
" set listchars=eol:$,trail:·,tab:>·
set laststatus=2

set autoindent
set smartindent
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set nowrap
set textwidth=80
set linebreak

set foldenable
set foldmethod=expr
set foldexpr=getline(v:lnum)=~'^\\s\\+#'  " fold comments
set foldminlines=4
set foldopen-=undo      " don't open folds when you undo stuff

set virtualedit=block

autocmd BufRead *irb-interactive* setl ft=ruby
autocmd BufRead nginx.conf setl ft=nginx
autocmd BufRead *.jst.ejs setl ft=jst

" Syntastic
" let g:syntastic_ruby_checkers = ['rubocop']
" let g:syntastic_javascript_checkers = ['jslint']

" Mappings
nnoremap <silent> <C-L> :nohls<cr>
nmap Q <nop>
nmap K <nop>
nmap U <nop>

" Remove trailing spaces
autocmd FileType ruby,eruby,javascript,jst,go autocmd BufWritePre <buffer> :%s/\s\+$//e

" Multiple cursors
let g:multi_cursor_start_key='<F5>'
let g:multi_cursor_next_key='<C-n>'
let g:multi_cursor_prev_key='<C-p>'
let g:multi_cursor_skip_key='<C-k>'
let g:multi_cursor_quit_key='<Esc>'

" Powerline
let g:Powerline_symbols='fancy'

" ctrlp
set wildignore+=*/tmp/*
set wildignore+=vendor/bundle,vendor/ruby
set wildignore+=*.png,*.jpg,*.gif,*.gem,*.o,*.so,*.swp,*.zip,*.log
let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'

" ctrlpBuffer
" nnoremap <silent> ,b <CR>:CtrlPBuffer<cr>
nnoremap <silent> <C-b> <CR>:CtrlPBuffer<cr>
" let g:ctrlp_show_hidden = 1

" gist
let g:gist_clip_command = 'pbcopy'

" rspec
au FileType ruby map <Leader>r :call RunCurrentSpecFile()<CR>
au FileType ruby map <Leader>s :call RunNearestSpec()<CR>
au FileType ruby map <Leader>a :call RunAllSpecs()<CR>
au FileType ruby let g:rspec_command = "!bundle exec rspec --drb {spec}"

" go
au FileType go nmap <Leader>s <Plug>(go-implements)
au FileType go nmap <Leader>i <Plug>(go-info)
au FileType go nmap <Leader>gd <Plug>(go-doc)
au FileType go nmap <Leader>gv <Plug>(go-doc-vertical)
au FileType go nmap <leader>r <Plug>(go-run)
au FileType go nmap <leader>b <Plug>(go-build)
au FileType go nmap <leader>t <Plug>(go-test)
au FileType go nmap <leader>c <Plug>(go-coverage)
au FileType go nmap <Leader>ds <Plug>(go-def-split)
au FileType go nmap <Leader>dv <Plug>(go-def-vertical)
au FileType go nmap <Leader>dt <Plug>(go-def-tab)

" easymotion
map <Leader> <Plug>(easymotion-prefix)

" NerdTree
nnoremap <silent> <C-n> :NERDTreeToggle<CR>
```

**Comment by faceleg** [comment]
Not sure what you want us to do here?

**Comment by sebdah** [comment]
@brunoadacosta, you'll just need to remap either NERDTree or vim-multiple-cursors

**Comment by brunoadacosta** [comment]
@sebdah I'll try, thanks

**Comment by sebdah** [comment]
@brunoadacosta I have NERDTree on `<leader>d` for example. `<leader>` in my case is `,`. 

Here's my NERDTree config: https://github.com/sebdah/vim-ide/blob/master/vim/config/plugins/nerd-tree.vim

**Comment by junkmechanic** [comment]
But this was not the case in earlier commits. As in normal mode <C-n> mapping would work just fine and then after activating multiple-cursors, <C-n> would select multiple instances as desired. But now, multiple-cursor seems to have hi-jacked the normal mode mapping for good. Is there a work around that does not involve having to remap the 'other' normal mode <C-n> mapping (nerdtree in OP's case).

Like setting a variable to check if multiple-cursors is activated or not and mapping accordingly. Is that possible?

Thanks

**Comment by brunoadacosta** [comment]
the problem is, my NERDTree is on <C-n>

**Comment by brunoadacosta** [comment]
In v2.2 this config works

" NerdTree
nnoremap <silent> <C-n> :NERDTreeToggle<CR>

" Multiple cursors
let g:multi_cursor_start_key='<F5>'
let g:multi_cursor_next_key='<C-n>'
let g:multi_cursor_prev_key='<C-p>'
let g:multi_cursor_skip_key='<C-k>'
let g:multi_cursor_quit_key='<Esc>'

**Comment by junkmechanic** [comment]
I have a similar case except that I have `nnoremap <C-N> :nohl<CR>` in my vimrc.
And now `let g:multi_cursor_use_default_mapping=0` is not being respected. Pressing `<C-N>` in normal mode (even without first pressing F6, which is my start key) starts multiple cursor mode instead of the desired action as defined in my mapping.

Is it because multiple-cursor overrides mappings unless they are "redefined" in another plugin (nerdtree in brunoadacosta's case)?

I am on commit `3199d3`.
I have had this setup (multiple-cursor + the above mapping) for quite some time and my recent pull of multiple-cursor seems to have created this problem. From my logs I can see that I moved from commit `bf8c1db` to the current one.

**Comment by junkmechanic** [comment]
I think I found the problem.
`:verbose map <c-n>` shows `:call multiple_cursors#new("n", 1)<CR> ` for normal mode.
Notice the `1` in the above map. Indicates that it was set on `lines 70/71` in the file `plugin/multiple_cursors.vim`. This is in turn is due to the condition on `lines 57/58`. The change was introduced to change the default behavior regarding word boundary selection.

I have initiated a pull request. Hope that helps.

Thanks

**Comment by faceleg** [comment]
Merged! Fixed now?

**Comment by junkmechanic** [comment]
Yup. Fixed. Thanks @faceleg . Request @brunoadacosta to close the issue if you find it meets your criterion.

**Comment by balta2ar** [comment]
@junkmechanic Is it possible to add some unit tests so that we don't break it in the future?

**Comment by junkmechanic** [comment]
Hi,
Ok bear with me as I have limited knowledge on vim and wrote my first rspec today.

Consider the following test
```
     1  describe "Multiple Cursors assigning start_word_key #2" do
     2    let(:filename) { 'test.txt' }
     3    let(:options) { ['let g:multi_cursor_start_key = "g<C-p>"'] }
     4
     5    specify "#word selection with only start_key defined" do
     6        before <<-EOF
     7          single word
     8          single word
     9          not a singleword
    10          single word
    11        EOF
    12
    13        type 'g<C-p><C-n><C-n>cdouble<Esc>'
    14        # type '<C-n><C-n><C-n>cdouble<Esc>'
    15
    16        after <<-EOF
    17          double word
    18          double word
    19          not a singleword
    20          double word
    21        EOF
    22    end
    23  end
```
It fails in its current form. But if I comment line 13 and uncomment line 14, it passes the test.
This shows that the required keys are not being mapped (`g<C-p>` to `multi_cursor_start_key` here).

My guess is that vim gets loaded with the plugin (multiple cursor) in the spec_helper and the mappings are done at that point (line 66 and beyond in `plugin/multiple_cursors.vim`). The option from line 3 above is set in the aftermath and has no effect since the mappings are already in place.
If thats true, then it renders the point of testing this void.

But of course, I could be wrong about this and there might be a way to invoke the mappings from the test spec. If someone could help me clear my understanding, I have already prepared the rest of the tests required for testing this feature which I could then share.

Thanks

**Comment by brunoadacosta** [comment]
Working! thanks
