### ISSUE TITLE
Feature Request: support for surround-plugin

### ISSUE THREAD

**Issue by hallosascha** [terryma/vim-multiple-cursors#147]
I would like to be able to create multiple cursors and then, surround the underlying words say with quotation marks using [surround.vim](https://github.com/tpope/vim-surround).
For example, I would like to change

```
Some text quote more text quote and even more text quote.
```

to

```
Some text "quote" more text "quote" and even more text "quote".
```

by issuing `S"` after entering the multiple cursor mode. This does not work yet. It would be really great to combine these two wonderful plugins to work together!

**Comment by faceleg** [comment]
Agree this would be great! PR always welcome

**Comment by nagarajasr** [comment]
```
:map B ysiw"
vB
```
works

**Comment by andrewdelprete** [comment]
@nagarajasr is there a way to set Vim up so it can wrap / surround a word with any character ? Your command above uses the quote, but I'd love to be able to use the same type of command for {} () "" or others w/ Multiple Cursors as well. Any thoughts? Thank you!

**Comment by nagarajasr** [comment]
sure go right ahead and use whatever character instead of ", it just works :-)
e.g., with ysiw{ or ysiw( the word is correctly surrounded with matching closing character (i.e., { with }, ( with ) ) with angle bracket <, the behaviour is slightly different, vim waits for further input terminated by carriage return, and the word is surrounded with a html start and end tag like this: 
if you key in ysiw<span<CR> you get  ```<span>word</span>```

**Comment by andrewdelprete** [comment]
Hey @nagarajasr thank you!

**Comment by karamfil** [comment]
While the proposed solution "kind of" works is not actually flexible :/
And you would need to do a lot of mappings: ys.. ds.. cs.. and text objects and enclosures, the combinations are quite a lot.

**Comment by balta2ar** [comment]
My new hope is this: https://github.com/neovim/neovim/issues/7257
