### ISSUE TITLE
Undo is character-wise instead of change block-wise

### ISSUE THREAD

**Issue by greduan** [terryma/vim-multiple-cursors#166]
I read some issues that were opened in the past about this, and it seems it was considered a fixed problem but this is still a problem for me (and my coworker as well).

If I select the word 'next' and change it (with `c`) to 'done', one undo operation (`u`) will remove the 'e', another one will remove the 'n', and so on.

This is not consistent with Vim's behaviour of the whole operation being undone, so one `u` would change 'done' to 'next'.

My friend is using the latest build of MacVim (I believe) and I'm using a recent (2 days ago) build of NeoVim. We're both on Macs.

**Comment by kamalmarhubi** [comment]
I see this in a recent neovim (0.1.2-dev, not sure which commit) and vim-multiple-cursors (0dfd3f9).

**Comment by tdehaeze** [comment]
Indeed, the issue is not present with Vim (8.0) but it is with NeoVim (v0.2.0)

**Comment by Bloodyfool** [comment]
I experience this issue inconsistently with 'insert at beginning of selection (`I`)'  as well as some other custom operations. Sometimes the undo applies to the whole word i inserted (expected behavior) and sometimes it undoes only 1, or sometimes 2 characters.

Somehow undo behavior is non deterministic.

I use vim 8.0
