### ISSUE TITLE
Cursors are still rendered after quitting multi cursors.

### ISSUE THREAD

**Issue by danijar** [terryma/vim-multiple-cursors#201]
The multi cursors stay in place after I quit multi cursors (mapped to <C-c> in my case). When I start new multi cursors, the old ones disappear.

**Comment by kylelamse** [comment]
I would love to take a stab at fixing this.  Although I'm not really sure around what line of the plugin file I should mess with. @faceleg Could you please give me some pointers?

**Comment by jeromedalbert** [comment]
I can confirm this issue.

### My setup

I have mapped `jj` to quit insert mode thanks to this mapping:
```vim
imap jj <esc>
```
To make this mapping work in vim-multiple-cursors, I also had to add this:
```vim
let g:multi_cursor_insert_maps = { 'j': 1 }
```

### Steps to reproduce

0. Select a couple words with `<c-n>`:
<img width="442" alt="screen shot 2016-07-09 at 11 05 13 am" src="https://cloud.githubusercontent.com/assets/236461/16709426/759d5a72-45c5-11e6-85db-b32ef3eea8b5.png">

0. Change the selections with `c` and type some text:
<img width="442" alt="screen shot 2016-07-09 at 11 05 38 am" src="https://cloud.githubusercontent.com/assets/236461/16709431/9e9ccad4-45c5-11e6-9698-dc6672ea4d83.png">

0. Press `jj` to escape. You can see that the multiple cursors are still there and have moved down (probably has something to do with `j`):
<img width="442" alt="screen shot 2016-07-09 at 11 05 50 am" src="https://cloud.githubusercontent.com/assets/236461/16709442/e443f2d8-45c5-11e6-8aaf-d972f55948cf.png">

If I press `<esc>` again, the cursors are cleared.

### Expected behavior

When I press `jj`, it should cleanly quit "multiple cursors mode" and clear all the cursors.

### Actual behavior

When I press `jj`, I am back to normal mode but the cursors are not removed. If I move the around with `h`/`j`/`k`/`l`, the cursors follow my movements.

### Failed attempts at workarounds

I have tried to do something like `imap jj <esc>:call multiple_cursors#quit()<cr>:call clearmatches()<cr>` but it doesn't work. Weirdly enough, if after pressing `jj` I manually type `:call multiple_cursors#quit()` and then `:call clearmatches()`, it kinda works (the original cursor position is not restored to the first match thoough). So for some reason, having everything in one mapping does not work.

**Comment by islam-taha** [comment]
I've the same issue, did anyone found a solution ?

**Comment by JoeWoodward** [comment]
+1 experiencing this too

**Comment by mboughaba** [comment]
> The multi cursors stay in place after I quit multi cursors (mapped to in my case). When I start new multi cursors, the old ones disappear.

This is not fixed. even with `<c-c>` *default mapping* it doesn't clear the selection.
`g:multi_cursor_exit_from_visual_mode = 1         " default`.

**Comment by antoinemadec** [comment]
@mboughaba that is a different issue, the issue @jeromedalbert reported has been fixed.
I just created #251 for the issue you are reporting.
