### ISSUE TITLE
Cant copy to system register

### ISSUE THREAD

**Issue by srghma** [terryma/vim-multiple-cursors#212]
Cursor on first character, neovim-qt, linux, clipboard=unnamed
```
Hardware Store
Beauty Parlor
Buy nail polish remover
Buy nails
```
I do `<C-v>3j<C-n>ve"+y` and any register didnt change

**Comment by antoinemadec** [comment]
@BjornMelgaard the reason why your command fails is because ```ve``` enters visual mode.

For now visual multiple-cursor mode does not support ```"<reg>y```.
I will try to look at the code when I have time to see if it can be implemented.

Meanwhile, a workaround is to not enter visual mode by doing: ```<C-v>3j<C-n>"+yiw```
I tested it and it works as expected.
