### ISSUE TITLE
Compatibility issue with neocomplete plugin

### ISSUE THREAD

**Issue by antlarr** [terryma/vim-multiple-cursors#214]
I had a problem when both vim-multiple-cursors and neocomplete.vim plugins are enabled and 
I have enabled neocomplete's auto_select with:

let g:neocomplete#enable_at_startup = 1
let g:neocomplete#enable_auto_select = 1

in my ~/.vimrc which starts autocompletion automatically while typing in insert mode.

So, if I create a couple of cursors and try to type anything, the neocomplete plugin writes garbage in every cursor (where garbage is: "<Plug>(neocomplete_start_auto_complete)").

Btw, the attached patch fixes this issue by disabling neocomplete's auto_select before creating a new cursor and restoring its value when quitting, but I'm not fluent with vim scripting so probably there's a nicer way to do that.

[fix-problem-with-neocomplete.txt](https://github.com/terryma/vim-multiple-cursors/files/783793/fix-problem-with-neocomplete.txt)

**Comment by balta2ar** [comment]
@antlarr Yes there is a cleaner way to do that: https://github.com/terryma/vim-multiple-cursors#interactions-with-other-plugins

In fact, I think this issue is a duplicate of https://github.com/terryma/vim-multiple-cursors/issues/144 and maybe https://github.com/terryma/vim-multiple-cursors/issues/143.

**Comment by antlarr** [comment]
Oops, I see it's already been addressed in the README file. Thanks and sorry for the noise.
