### ISSUE TITLE
binding kj for exit?

### ISSUE THREAD

**Issue by hems** [terryma/vim-multiple-cursors#226]
I tried to bind kj for exit by doing

````
let g:multi_cursor_quit_key='kj'
````

but it doesn't seem to work, am i doing something wrong?

**Comment by hems** [comment]
just now i tried doing the map this way, but also no success:

````vimscript
" remapping vim-multiple-cursors
let g:multi_cursor_use_default_mapping=0

" Default mapping
let g:multi_cursor_next_key='<C-n>'
let g:multi_cursor_prev_key='<C-p>'
let g:multi_cursor_skip_key='<C-x>'
let g:multi_cursor_quit_key='kj'
````

**Comment by eapache** [comment]
The plugin as written does not support multi-character bindings (things like `<C-n>` still work because vim effectively converts them into a single event under the hood).

I haven't looked too closely, but the to make it work it may just be enough to change `s:last_char()` to `s:char()` in the exit function: https://github.com/terryma/vim-multiple-cursors/blob/a97dab5bc440bf0a7b62bb2de4479963a888f4ff/autoload/multiple_cursors.vim#L1059.

It wouldn't surprise me if more work was needed though, probably around the `multi_cursor_*_maps` variables the plugin uses to detect regular multi-key commands.

**Comment by hems** [comment]
@eapache thanks a lot! will have a look at it when i get a chance, still baby steps on vimscript

**Comment by antoinemadec** [comment]
The same goes for g:multi_cursor_start_key

**Comment by TornaxO7** [comment]
So it won't be possible to add a keybinding like that?
```vim
" ------------------
"  mutiple-cursors
" ------------------
let g:multi_cursor_quit_key 		   = '<Esc>'
let g:multi_cursor_start_word_key 	   = '<leader>mn'
"let g:multi_cursor_select_all_word_key = '<leader>my'
let g:multi_cursor_start_key           = '<leader>mS'
let g:multi_cursor_select_all_key      = '<leader>mas'
let g:multi_cursor_next_key            = '<leader>mn'
let g:multi_cursor_prev_key            = '<leader>mp'
let g:multi_cursor_skip_key            = '<leader>ms'

```
Because some keybindings work like the `<leader>mn' keybinding.
