### ISSUE TITLE
Question about mappings

### ISSUE THREAD

**Issue by alextes** [terryma/vim-multiple-cursors#287]
Since this plugin grabs `<C-n>` by default, a rather _premium_ key bind if you will, I'm curious, how do you navigate between buffers? For me, and I imagined many others `<C-n>` is bound to `:bn <CR>`.

So now I'm curious, how do you navigate buffers?

**Comment by antoinemadec** [comment]
Hi @alextes , I personally don't map ```<C-n>``` for ```:bn <CR>```.
To navigate buffers I use ```vim-fzf``` and map ```<leader>be``` (Buffer Explorer) to ```:Buffers<CR>```.

Vim mappings are pretty different between people because we all have different work flows.
There is just no way everyone in the world will agree on 1 set of universal mappings, that's why plugins usually offer the possibility to change the default mappings:
  https://github.com/terryma/vim-multiple-cursors#mapping

I hope this helps!

Cheers,
Antoine
