### ISSUE TITLE
multiple cursors break keymapping

### ISSUE THREAD

**Issue by tusj** [terryma/vim-multiple-cursors#47]
I have mapped jj to escape in insert mode, but this is broken when multiple cursors is used. That is, the jj is interpreted as raw keystrokes.

**Comment by still-dreaming-1** [comment]
I am having this same problem. When entering text from insert mode, I normally press `kk` to go back to normal mode. I disabled `esc` from working in order to train myself to use `kk` instead. When multiple cursors are going and I use `c` to rename a variable, it throws me off to not have the mappings I am used to. Issue https://github.com/terryma/vim-multiple-cursors/issues/46 does not seem like a duplicate to me as I believe they are reporting unwanted text getting entered into the buffer and someone reported the same thing without custom mappings. Even if this is a duplicate the other issue was closed with no reason given.

**Comment by faceleg** [comment]
Reopened #46
