### ISSUE TITLE
Implement A and I in Visual mode (similar to vim's Visual block mode)

### ISSUE THREAD

**Issue by johan-adriaans** [terryma/vim-multiple-cursors#55]
When I select a bunch of lines or words and press shift-i (What normally do in visual block mode) the plugin jumps to insert mode like it should but it also injects: ":call <SNR>74_apply_user_input_next('i')" into the code at every cursor.

I am using VIM version 7.3.429 and using the latest vim-multiple-cursors.

Thanks for the great plugin BTW! :)

**Comment by Hubro** [comment]
I just got bitten by this bug today, thought I'd bump this bug report

**Comment by balta2ar** [comment]
@faceleg How about renaming this one to "Implement A and I in Visual mode (similar to vim's Visual block mode)"?

**Comment by acornejo** [comment]
just ran into this problem, it is really unfortunate since I've been spolied by I and A are used a lot in visual block mode.

i tried looking through the code, but can't really tell what is going on. Anyone know of any workarounds? 

Given that A can be achieved by pressing va, and I can be achived by vi, one would think there would be an easy workaround (but I am guessing there aren't, since this issue is still open after 2 years)

**Comment by eapache** [comment]
So I just did a bit of digging here, and as far as I can tell the plugin is doing everything right. This is either a bug or an inherent limitation of vim itself.

Specifically, the plugin works by capturing what you type and then running `feedkeys(input . "\<Plug>(multiple-cursors-apply)")`. This appended plugin map is supposed to get turned into a function call by vim, and this occurs correctly in most cases (even when e.g. the input string puts you into insert mode, the `\<Plug>` escape ignores that). However, when you use `A` or `I` to enter insert mode, the plug escape is not respected and is inserted directly as text. I'm not sure how or why; as far as I know vim is doing the wrong thing here.

**Comment by acornejo** [comment]
@eapache I saw that too. I think it's a bug that stems from the way the plug in handles modes, but maybe you are write and it's bin itself (somehow that feels less likely)

The plug thing does work in that vim correctly puts the number and function call name in there instead of the pl. Tthe problem seems to be that this text was pasted while in insert mode instead of putting it in the command line. The result is that instead of calling the function we see its name pasted in the text.

The mapping is prepended with some control characters meant to escape insert mode, then inseft a colon (to go to command mode) and then put the plug. These are somehow not working, perhaps because in the same feed keys call we have a character that is changing the mode?

**Comment by eapache** [comment]
> These are somehow not working, perhaps because in the same feed keys call we have a character that is changing the mode?

No, the same path is hit for simpler keys like `i` which work just fine.

**Comment by acornejo** [comment]
@eapache interesting. This is not the case for me, neither a, i A or I work fine. They work fine if I press 'v' first, but in normal mode only keys like c,s or d work as expected. Here is a screencast:

https://asciinema.org/a/459ggvlbifbxvb9p10jks7pcw

I would be curious to see the same experiment in your machine.

**Comment by eapache** [comment]
At least part of the confusion is that you're not *in* normal mode, you're in visual block mode. Pressing `v` takes you into normal mode.

`i`, `a`, etc. do not work in visual-block mode in regular vim, so I wouldn't expect them to work in multi-cursor visual-block mode.

**Comment by tonchis** [comment]
@eapache Thank you!! :tada: :balloon:
